### ISSUE TITLE
Installing with Homebrew Cask

### ISSUE THREAD

**Issue by miccal** [jpadilla/rabbitmqapp#2]
@jpadilla the name of the Cask related to your app has changed [here](https://github.com/caskroom/homebrew-cask/pull/28892).

Please update your `README.md` to:
```
brew cask install rabbitmq-app
```

Thanks.

**Comment by jpadilla** [comment]
@miccal thank you very much for reaching out about the rename. I'm wondering if https://github.com/caskroom/homebrew-cask/pull/23956 should've been handled like https://github.com/caskroom/homebrew-cask/pull/28892?

**Comment by miccal** [comment]
@jpadilla sorry I do not know, I was not an active member of Cask during the deduplication process.

**Comment by adidalal** [comment]
@jpadilla Should be handled the same way - starting the process to re-add it as `redis-app`

**Comment by jpadilla** [comment]
@adidalal thanks!

**Comment by jpadilla** [comment]
Closed via d2831aa
