### ISSUE TITLE
After installation, Management UI doesn't work

### ISSUE THREAD

**Issue by kenorb** [jpadilla/rabbitmqapp#5]
I've installed 3.6.1-build.1/RabbitMQ.zip via:

    brew cask install caskroom/cask/rabbitmq-app

The app reads it's running on 5672, but after clicking on _Management UI_, nothing is shown. The connection is refused.

**Comment by kenorb** [comment]
Ok, it seems to work after running `brew services start rabbitmq`.

Then it'll take a while till it's started:

```
$ netstat -na | grep 15672
tcp4       0      0  *.15672                *.*                    LISTEN    
```

Then access _Management UI_ by going to http://localhost:15672/ address.

**Comment by jdickey** [comment]
@kenorb Where is the username/password defined that is being prompted for in the Management UI?

**Comment by kenorb** [comment]
> @kenorb Where is the username/password defined that is being prompted for in the Management UI?

I'm not sure, raise a new ticket for it.
